//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorstApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class internet_magazEntities : DbContext
    {
        public internet_magazEntities()
            : base("name=internet_magazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Изображения_товаров> Изображения_товаров { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<Комплектующие> Комплектующие { get; set; }
        public virtual DbSet<Компьютеры> Компьютеры { get; set; }
        public virtual DbSet<Конфигурация> Конфигурация { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Статистика_по_тестам> Статистика_по_тестам { get; set; }
        public virtual DbSet<Популярные> Популярные { get; set; }
    }
}
