//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorstApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int id_заказа { get; set; }
        public string дата { get; set; }
        public string статус { get; set; }
        public int ID_пользователя { get; set; }
        public int id_продукта { get; set; }
    }
}
