//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorstApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int ID { get; set; }
        public string Имя { get; set; }
        public string Почта { get; set; }
        public string Индекс { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Пароль { get; set; }
    }
}
