//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorstApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статистика_по_тестам
    {
        public int ID { get; set; }
        public Nullable<int> Продукт { get; set; }
        public string Приложение { get; set; }
        public string Разрешение { get; set; }
        public string FPS { get; set; }
    }
}
